openapi: 3.0.2
info:
  title: 'News Portal'
  version: "0.1"
paths:
  /serializers/posts/:
    get:
      operationId: listPosts
      description: 'List of Posts'
      parameters: []
      responses:
        '200':
          content:
          application/json:
            schema:
              type: array
              items:
                  $ref: '#/components/schemas/Post'
          description: ''
      tags:
        - posts

    post:
      operationId: createPost
      description: 'Create a Post'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: ''
      tags:
        - posts

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        author:
          type: string
          maxLength: 64
        title:
          type: string
          maxLength: 300
        text:
          type: string
          maxLength:
        category:
          type: string
          maxLength: 64
      required:
        - author
        - title
        - text
        - category