openapi: 3.0.2
info:
  title: 'News Portal'
  version: "0.1"
paths:
  /:
    get:
      operationId: listPosts
      description: 'List of Posts'
      parameters: []
      responses:
        '200':
          content:
          application/json:
            schema:
              type: array
              items:
                  $ref: '#/components/schemas/Post'
          description: ''
      tags:
        - posts

    post:
      operationId: createPost
      description: 'Create a Post'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: ''
      tags:
        - posts

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 64
      required:
        - name